In [15]:
from staNMF import staNMF
from staNMF import spams_nmf
import numpy as np

In [2]:
nmf = spams_nmf(n_components=2)

In [17]:
NMF(10).fit(np.random.uniform(0,1,(100,20))).n_iter_

199

In [20]:
from sklearn.utils import check_random_state

In [22]:
rng = np.random.RandomState(100)

In [27]:
rng.uniform(0,1,(10,10))#(range(10),10,replace=True)

array([[0.29887635, 0.56874553, 0.17862432, 0.5325737 , 0.64669147,
        0.14206538, 0.58138896, 0.47918994, 0.38641911, 0.44046495],
       [0.40475733, 0.44225404, 0.03012328, 0.77600531, 0.55095838,
        0.3810734 , 0.52926578, 0.9568769 , 0.17582131, 0.11830284],
       [0.86294567, 0.07486688, 0.82509486, 0.83613181, 0.07539491,
        0.01140079, 0.04842057, 0.35712271, 0.66569338, 0.01138961],
       [0.10791777, 0.9010131 , 0.79487876, 0.81146098, 0.64027806,
        0.62477951, 0.14550751, 0.5702159 , 0.0651125 , 0.31341257],
       [0.21706577, 0.52695039, 0.42710838, 0.98263043, 0.14045149,
        0.7484116 , 0.78884039, 0.73039662, 0.84561834, 0.55619038],
       [0.05686271, 0.88672457, 0.31441695, 0.56039187, 0.2540144 ,
        0.9349621 , 0.03424494, 0.68654496, 0.43893494, 0.97772095],
       [0.47738415, 0.23895263, 0.93235066, 0.13671513, 0.17192781,
        0.50305449, 0.05585289, 0.29766707, 0.92771357, 0.38659638],
       [0.46212547, 0.57862899, 0.1139206

In [28]:
from sklearn.decomposition.nmf import _initialize_nmf

In [54]:
np.random.seed(None)
_initialize_nmf(np.eye(10), 1, 'random')

(array([[0.52083907],
        [0.59310116],
        [0.75356297],
        [0.43430839],
        [0.11206552],
        [0.14575903],
        [0.49271947],
        [0.21067894],
        [0.49967846],
        [0.50551794]]),
 array([[0.09155186, 0.35798257, 0.26684915, 0.25036661, 0.18874894,
         0.05854666, 0.37476728, 0.32963969, 0.12990297, 0.01319484]]))

In [21]:
inspect.getsource(check_random_state)

'def check_random_state(seed):\n    """Turn seed into a np.random.RandomState instance\n\n    Parameters\n    ----------\n    seed : None | int | instance of RandomState\n        If seed is None, return the RandomState singleton used by np.random.\n        If seed is an int, return a new RandomState instance seeded with seed.\n        If seed is already a RandomState instance, return it.\n        Otherwise raise ValueError.\n    """\n    if seed is None or seed is np.random:\n        return np.random.mtrand._rand\n    if isinstance(seed, (numbers.Integral, np.integer)):\n        return np.random.RandomState(seed)\n    if isinstance(seed, np.random.RandomState):\n        return seed\n    raise ValueError(\'%r cannot be used to seed a numpy.random.RandomState\'\n                     \' instance\' % seed)\n'

In [19]:
NMF().__class__

sklearn.decomposition.nmf.NMF

In [7]:
from sklearn.decomposition import NMF
from sklearn.base import TransformerMixin
import inspect

In [5]:
inspect(NMF.__class__)

TypeError: 'module' object is not callable

In [10]:
inspect.getsource(NMF)

'class NMF(BaseEstimator, TransformerMixin):\n    r"""Non-Negative Matrix Factorization (NMF)\n\n    Find two non-negative matrices (W, H) whose product approximates the non-\n    negative matrix X. This factorization can be used for example for\n    dimensionality reduction, source separation or topic extraction.\n\n    The objective function is::\n\n        0.5 * ||X - WH||_Fro^2\n        + alpha * l1_ratio * ||vec(W)||_1\n        + alpha * l1_ratio * ||vec(H)||_1\n        + 0.5 * alpha * (1 - l1_ratio) * ||W||_Fro^2\n        + 0.5 * alpha * (1 - l1_ratio) * ||H||_Fro^2\n\n    Where::\n\n        ||A||_Fro^2 = \\sum_{i,j} A_{ij}^2 (Frobenius norm)\n        ||vec(A)||_1 = \\sum_{i,j} abs(A_{ij}) (Elementwise L1 norm)\n\n    For multiplicative-update (\'mu\') solver, the Frobenius norm\n    (0.5 * ||X - WH||_Fro^2) can be changed into another beta-divergence loss,\n    by changing the beta_loss parameter.\n\n    The objective function is minimized with an alternating minimization of W\n

In [11]:
import numpy as np

In [20]:
inspect.getargvalues(staNMF)

AttributeError: type object 'staNMF' has no attribute 'f_code'